Found local copy...
Loading...
Done!
[I 2025-09-05 20:58:48,588] A new study created in RDB with name: __init__
[I 2025-09-05 20:58:48,825] A new study created in RDB with name: RDKitFP_RF_Caco2_Wang_0
[I 2025-09-05 20:58:48,865] A new study created in RDB with name: RDKitFP_RF_Caco2_Wang_1
[I 2025-09-05 20:58:48,940] A new study created in RDB with name: RDKitFP_RF_Caco2_Wang_2
[I 2025-09-05 20:58:49,055] A new study created in RDB with name: RDKitFP_RF_Caco2_Wang_3
[I 2025-09-05 20:59:19,799] Trial 0 finished with value: 0.2838012942309915 and parameters: {'n_estimators': 50, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.2838012942309915.
[I 2025-09-05 20:59:20,156] Trial 0 finished with value: 0.30933116606068184 and parameters: {'n_estimators': 50, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.30933116606068184.
[I 2025-09-05 21:00:05,809] Trial 0 finished with value: 0.28169488440157836 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.28169488440157836.
[I 2025-09-05 21:00:06,872] Trial 0 finished with value: 0.3258889303972404 and parameters: {'n_estimators': 200, 'max_depth': 5, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.3258889303972404.
[I 2025-09-05 21:01:00,995] Trial 1 finished with value: 0.2919282202737621 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.28169488440157836.
[I 2025-09-05 21:01:27,160] Trial 1 finished with value: 0.3274147506601869 and parameters: {'n_estimators': 200, 'max_depth': 5, 'min_samples_split': 10, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.3258889303972404.
[I 2025-09-05 21:01:58,786] Trial 2 finished with value: 0.29421235743991486 and parameters: {'n_estimators': 50, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 4}. Best is trial 2 with value: 0.29421235743991486.
[I 2025-09-05 21:02:01,827] Trial 1 finished with value: 0.29401162444272533 and parameters: {'n_estimators': 200, 'max_depth': 20, 'min_samples_split': 5, 'min_samples_leaf': 1}. Best is trial 1 with value: 0.29401162444272533.
[I 2025-09-05 21:02:13,089] Trial 1 finished with value: 0.2768631747755609 and parameters: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 4}. Best is trial 1 with value: 0.2768631747755609.
[I 2025-09-05 21:02:22,522] Trial 2 finished with value: 0.3365671137025553 and parameters: {'n_estimators': 50, 'max_depth': 5, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 1 with value: 0.29401162444272533.
[I 2025-09-05 21:02:36,742] Trial 3 finished with value: 0.32823774447014603 and parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 4}. Best is trial 2 with value: 0.29421235743991486.
[I 2025-09-05 21:02:54,843] Trial 3 finished with value: 0.3051287807639814 and parameters: {'n_estimators': 50, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 1}. Best is trial 1 with value: 0.29401162444272533.
[I 2025-09-05 21:03:10,262] Trial 2 finished with value: 0.2830243838188737 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 4}. Best is trial 1 with value: 0.2768631747755609.
[I 2025-09-05 21:03:49,882] Trial 2 finished with value: 0.2816856938367425 and parameters: {'n_estimators': 300, 'max_depth': 20, 'min_samples_split': 2, 'min_samples_leaf': 4}. Best is trial 2 with value: 0.2816856938367425.
[I 2025-09-05 21:03:52,680] Trial 4 finished with value: 0.3271759345345037 and parameters: {'n_estimators': 200, 'max_depth': 5, 'min_samples_split': 10, 'min_samples_leaf': 1}. Best is trial 2 with value: 0.29421235743991486.
[I 2025-09-05 21:04:11,758] Trial 3 finished with value: 0.3322705449250712 and parameters: {'n_estimators': 50, 'max_depth': 5, 'min_samples_split': 10, 'min_samples_leaf': 1}. Best is trial 2 with value: 0.2816856938367425.
[I 2025-09-05 21:04:45,672] Trial 3 finished with value: 0.27345072242888957 and parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 5, 'min_samples_leaf': 1}. Best is trial 3 with value: 0.27345072242888957.
[I 2025-09-05 21:05:37,877] Trial 4 finished with value: 0.2983978274401308 and parameters: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 4}. Best is trial 1 with value: 0.29401162444272533.
[I 2025-09-05 21:06:04,943] Trial 4 finished with value: 0.28400755526280963 and parameters: {'n_estimators': 200, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 1}. Best is trial 2 with value: 0.2816856938367425.
[I 2025-09-05 21:06:32,544] Trial 5 finished with value: 0.2913521736894274 and parameters: {'n_estimators': 300, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 4}. Best is trial 5 with value: 0.2913521736894274.
[I 2025-09-05 21:06:34,568] Trial 5 finished with value: 0.30187656368656407 and parameters: {'n_estimators': 100, 'max_depth': 20, 'min_samples_split': 2, 'min_samples_leaf': 4}. Best is trial 1 with value: 0.29401162444272533.
[I 2025-09-05 21:06:41,533] Trial 4 finished with value: 0.2779925742466049 and parameters: {'n_estimators': 200, 'max_depth': 20, 'min_samples_split': 10, 'min_samples_leaf': 1}. Best is trial 3 with value: 0.27345072242888957.
[I 2025-09-05 21:07:41,439] Trial 5 finished with value: 0.28215424384880156 and parameters: {'n_estimators': 100, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 4}. Best is trial 3 with value: 0.27345072242888957.
[I 2025-09-05 21:08:36,922] Trial 6 finished with value: 0.28400492599970295 and parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 10, 'min_samples_leaf': 4}. Best is trial 3 with value: 0.27345072242888957.
[I 2025-09-05 21:08:38,255] Trial 5 finished with value: 0.274246688799625 and parameters: {'n_estimators': 200, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 5 with value: 0.274246688799625.
[I 2025-09-05 21:10:22,924] Trial 6 finished with value: 0.2814531444554253 and parameters: {'n_estimators': 300, 'max_depth': 20, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 6 with value: 0.2814531444554253.
[I 2025-09-05 21:10:26,208] Trial 6 finished with value: 0.291333281753943 and parameters: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 6 with value: 0.291333281753943.
[I 2025-09-05 21:10:29,629] Trial 6 finished with value: 0.2830791348669379 and parameters: {'n_estimators': 200, 'max_depth': 15, 'min_samples_split': 5, 'min_samples_leaf': 4}. Best is trial 5 with value: 0.274246688799625.
[I 2025-09-05 21:10:51,375] Trial 7 finished with value: 0.32872528757706804 and parameters: {'n_estimators': 50, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 1}. Best is trial 5 with value: 0.274246688799625.
[I 2025-09-05 21:11:06,562] Trial 7 finished with value: 0.30129881432536104 and parameters: {'n_estimators': 50, 'max_depth': 20, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 6 with value: 0.291333281753943.
[I 2025-09-05 21:11:23,434] Trial 7 finished with value: 0.2774899054212174 and parameters: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 10, 'min_samples_leaf': 2}. Best is trial 3 with value: 0.27345072242888957.
[I 2025-09-05 21:11:28,616] Trial 8 finished with value: 0.28242567329140106 and parameters: {'n_estimators': 50, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 1}. Best is trial 5 with value: 0.274246688799625.
[I 2025-09-05 21:11:44,676] Trial 8 finished with value: 0.32647943761589615 and parameters: {'n_estimators': 50, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 1}. Best is trial 3 with value: 0.27345072242888957.
[I 2025-09-05 21:12:03,400] Trial 8 finished with value: 0.3037477732692826 and parameters: {'n_estimators': 100, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 2}. Best is trial 6 with value: 0.291333281753943.
[I 2025-09-05 21:13:18,527] Trial 9 finished with value: 0.323842572523702 and parameters: {'n_estimators': 300, 'max_depth': 5, 'min_samples_split': 10, 'min_samples_leaf': 4}. Best is trial 5 with value: 0.274246688799625.
[I 2025-09-05 21:13:18,546] Trial 9 finished with value: 0.2947413680034405 and parameters: {'n_estimators': 100, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 6 with value: 0.291333281753943.
[I 2025-09-05 21:13:18,565] Trial 7 finished with value: 0.28125022309171605 and parameters: {'n_estimators': 200, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 7 with value: 0.28125022309171605.
[I 2025-09-05 21:13:18,584] Trial 9 finished with value: 0.2742050036580657 and parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 3 with value: 0.27345072242888957.
[I 2025-09-05 21:14:59,133] Trial 8 finished with value: 0.2838425393709683 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 1}. Best is trial 7 with value: 0.28125022309171605.
[I 2025-09-05 21:14:59,190] Trial 10 finished with value: 0.3226466697890917 and parameters: {'n_estimators': 200, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 1}. Best is trial 3 with value: 0.27345072242888957.
[I 2025-09-05 21:15:46,195] Trial 10 finished with value: 0.274246688799625 and parameters: {'n_estimators': 200, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 5 with value: 0.274246688799625.
[I 2025-09-05 21:16:21,063] Trial 9 finished with value: 0.28704697347917585 and parameters: {'n_estimators': 50, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 2}. Best is trial 7 with value: 0.28125022309171605.
[I 2025-09-05 21:16:21,131] A new study created in RDB with name: RDKitFP_RF_Caco2_Wang_4
[W 2025-09-05 21:16:21,097] Trial 11 failed with parameters: {} because of the following error: StorageInternalError('An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. ').
Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 77, in _create_scoped_session
    yield session
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 807, in _get_trials
    models.StudyModel.find_or_raise_by_id(study_id, session)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/models.py", line 71, in find_or_raise_by_id
    study = query.one_or_none()
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2845, in one_or_none
    return self._iter().one_or_none()
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2903, in _iter
    result = self.session.execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1696, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1631, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context
    self._handle_dbapi_exception(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: SELECT studies.study_id AS studies_study_id, studies.study_name AS studies_study_name 
FROM studies 
WHERE studies.study_id = ?]
[parameters: (2,)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/study/_optimize.py", line 201, in _run_trial
    value_or_values = func(trial)
  File "/myriadfs/home/ucnwdma/Scratch/UCL_internship/code/study_manager.py", line 81, in objective
    hyperparams = model_class.get_hyperparameter_space(trial)
  File "/myriadfs/home/ucnwdma/Scratch/UCL_internship/code/models.py", line 271, in get_hyperparameter_space
    'n_estimators': trial.suggest_categorical('n_estimators', [50, 100, 200, 300]),
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/trial/_trial.py", line 406, in suggest_categorical
    return self._suggest(name, CategoricalDistribution(choices=choices))
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/trial/_trial.py", line 635, in _suggest
    param_value = self.study.sampler.sample_independent(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/samplers/_tpe/sampler.py", line 455, in sample_independent
    trials = study._get_trials(deepcopy=False, states=states, use_cache=True)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/study/study.py", line 277, in _get_trials
    self._thread_local.cached_all_trials = self._storage.get_all_trials(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_cached_storage.py", line 219, in get_all_trials
    self._read_trials_from_remote_storage(study_id)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_cached_storage.py", line 240, in _read_trials_from_remote_storage
    trials = self._backend._get_trials(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 857, in _get_trials
    trials = [self._build_frozen_trial_from_trial_model(trial) for trial in trial_models]
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 95, in _create_scoped_session
    raise optuna.exceptions.StorageInternalError(message) from e
optuna.exceptions.StorageInternalError: An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. 
[W 2025-09-05 21:16:21,143] Trial 11 failed with value None.
[I 2025-09-05 21:16:59,273] Trial 10 finished with value: 0.2899666539442839 and parameters: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 10 with value: 0.2899666539442839.
[I 2025-09-05 21:16:59,314] Trial 0 finished with value: 0.28648690047728226 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.28648690047728226.
[I 2025-09-05 21:16:59,428] A new study created in RDB with name: RDKitFP_RF_Caco2_Wang_5
[I 2025-09-05 21:19:53,214] Trial 10 finished with value: 0.28125022309171605 and parameters: {'n_estimators': 200, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 7 with value: 0.28125022309171605.
[I 2025-09-05 21:20:41,091] Trial 1 finished with value: 0.26751083998420383 and parameters: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 1 with value: 0.26751083998420383.
[I 2025-09-05 21:20:41,214] Trial 0 finished with value: 0.28853107837212305 and parameters: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.28853107837212305.
[I 2025-09-05 21:22:23,775] Trial 11 finished with value: 0.2899666539442839 and parameters: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 10 with value: 0.2899666539442839.
[I 2025-09-05 21:22:23,787] Trial 1 finished with value: 0.3103718351709473 and parameters: {'n_estimators': 50, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.28853107837212305.
[I 2025-09-05 21:22:23,807] Trial 11 finished with value: 0.28125022309171605 and parameters: {'n_estimators': 200, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 7 with value: 0.28125022309171605.
[I 2025-09-05 21:22:23,817] Trial 2 finished with value: 0.285826186023653 and parameters: {'n_estimators': 100, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 4}. Best is trial 1 with value: 0.26751083998420383.
[I 2025-09-05 21:25:16,108] Trial 3 finished with value: 0.2744566130200663 and parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 1 with value: 0.26751083998420383.
[I 2025-09-05 21:25:19,752] Trial 12 finished with value: 0.28125022309171605 and parameters: {'n_estimators': 200, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 7 with value: 0.28125022309171605.
[W 2025-09-05 21:25:40,388] Trial 4 failed with parameters: {} because of the following error: StorageInternalError('An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. ').
Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 77, in _create_scoped_session
    yield session
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 807, in _get_trials
    models.StudyModel.find_or_raise_by_id(study_id, session)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/models.py", line 71, in find_or_raise_by_id
    study = query.one_or_none()
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2845, in one_or_none
    return self._iter().one_or_none()
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2903, in _iter
    result = self.session.execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1696, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1631, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context
    self._handle_dbapi_exception(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: SELECT studies.study_id AS studies_study_id, studies.study_name AS studies_study_name 
FROM studies 
WHERE studies.study_id = ?]
[parameters: (6,)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/study/_optimize.py", line 201, in _run_trial
    value_or_values = func(trial)
  File "/myriadfs/home/ucnwdma/Scratch/UCL_internship/code/study_manager.py", line 81, in objective
    hyperparams = model_class.get_hyperparameter_space(trial)
  File "/myriadfs/home/ucnwdma/Scratch/UCL_internship/code/models.py", line 271, in get_hyperparameter_space
    'n_estimators': trial.suggest_categorical('n_estimators', [50, 100, 200, 300]),
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/trial/_trial.py", line 406, in suggest_categorical
    return self._suggest(name, CategoricalDistribution(choices=choices))
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/trial/_trial.py", line 635, in _suggest
    param_value = self.study.sampler.sample_independent(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/samplers/_tpe/sampler.py", line 455, in sample_independent
    trials = study._get_trials(deepcopy=False, states=states, use_cache=True)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/study/study.py", line 277, in _get_trials
    self._thread_local.cached_all_trials = self._storage.get_all_trials(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_cached_storage.py", line 219, in get_all_trials
    self._read_trials_from_remote_storage(study_id)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_cached_storage.py", line 240, in _read_trials_from_remote_storage
    trials = self._backend._get_trials(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 857, in _get_trials
    trials = [self._build_frozen_trial_from_trial_model(trial) for trial in trial_models]
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 95, in _create_scoped_session
    raise optuna.exceptions.StorageInternalError(message) from e
optuna.exceptions.StorageInternalError: An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. 
[W 2025-09-05 21:25:40,389] Trial 4 failed with value None.
[I 2025-09-05 21:25:52,769] A new study created in RDB with name: RDKitFP_RF_Caco2_Wang_6
[I 2025-09-05 21:27:28,583] Trial 2 finished with value: 0.2862434898991479 and parameters: {'n_estimators': 300, 'max_depth': 20, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 2 with value: 0.2862434898991479.
[I 2025-09-05 21:27:28,584] Trial 12 finished with value: 0.2899666539442839 and parameters: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 10 with value: 0.2899666539442839.
[I 2025-09-05 21:28:22,013] A new study created in RDB with name: RDKitFP_RF_Caco2_Wang_7
[I 2025-09-05 21:28:27,828] Trial 0 finished with value: 0.2730393600728001 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.2730393600728001.
[I 2025-09-05 21:28:33,502] Trial 13 finished with value: 0.28125022309171605 and parameters: {'n_estimators': 200, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 7 with value: 0.28125022309171605.
[I 2025-09-05 21:29:02,677] Trial 3 finished with value: 0.30997459821697404 and parameters: {'n_estimators': 50, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 4}. Best is trial 2 with value: 0.2862434898991479.
[I 2025-09-05 21:30:41,424] Trial 1 finished with value: 0.28874173254776053 and parameters: {'n_estimators': 50, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.2730393600728001.
[I 2025-09-05 21:30:58,972] Trial 0 finished with value: 0.28231409945109726 and parameters: {'n_estimators': 100, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.28231409945109726.
[I 2025-09-05 21:31:26,664] Trial 4 finished with value: 0.29531633200721474 and parameters: {'n_estimators': 200, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 2}. Best is trial 2 with value: 0.2862434898991479.
[I 2025-09-05 21:31:26,691] Trial 14 finished with value: 0.28125022309171605 and parameters: {'n_estimators': 200, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 7 with value: 0.28125022309171605.
[I 2025-09-05 21:31:26,795] A new study created in RDB with name: RDKitFP_RF_Caco2_Wang_8
[I 2025-09-05 21:32:23,800] Trial 2 finished with value: 0.2858361051481215 and parameters: {'n_estimators': 50, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.2730393600728001.
[I 2025-09-05 21:32:35,081] A new study created in RDB with name: RDKitFP_RF_Caco2_Wang_9
[I 2025-09-05 21:32:35,134] Trial 0 finished with value: 0.28172423048203693 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.28172423048203693.
[I 2025-09-05 21:34:17,956] Trial 5 finished with value: 0.29516508047513884 and parameters: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 10, 'min_samples_leaf': 2}. Best is trial 2 with value: 0.2862434898991479.
[I 2025-09-05 21:34:18,155] Trial 3 finished with value: 0.2794077311506978 and parameters: {'n_estimators': 100, 'max_depth': 20, 'min_samples_split': 5, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.2730393600728001.
[I 2025-09-05 21:35:38,954] Trial 1 finished with value: 0.2799209323413995 and parameters: {'n_estimators': 300, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 1 with value: 0.2799209323413995.
[I 2025-09-05 21:35:39,138] Trial 4 finished with value: 0.28203212324727195 and parameters: {'n_estimators': 50, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.2730393600728001.
[I 2025-09-05 21:35:53,652] Trial 6 finished with value: 0.29440073853178095 and parameters: {'n_estimators': 300, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 4}. Best is trial 2 with value: 0.2862434898991479.
[I 2025-09-05 21:36:26,280] Trial 2 finished with value: 0.2889095025354238 and parameters: {'n_estimators': 100, 'max_depth': 20, 'min_samples_split': 2, 'min_samples_leaf': 4}. Best is trial 1 with value: 0.2799209323413995.
[I 2025-09-05 21:36:26,325] Trial 5 finished with value: 0.27599515738246644 and parameters: {'n_estimators': 100, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.2730393600728001.
[I 2025-09-05 21:37:23,581] Trial 7 finished with value: 0.2953996426270705 and parameters: {'n_estimators': 50, 'max_depth': 15, 'min_samples_split': 5, 'min_samples_leaf': 1}. Best is trial 2 with value: 0.2862434898991479.
[I 2025-09-05 21:37:54,883] Trial 3 finished with value: 0.28135268320470497 and parameters: {'n_estimators': 200, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 2}. Best is trial 1 with value: 0.2799209323413995.
[I 2025-09-05 21:38:21,100] Trial 6 finished with value: 0.28572949765509287 and parameters: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 10, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.2730393600728001.
[I 2025-09-05 21:38:21,125] Trial 8 finished with value: 0.29912177012131297 and parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 4}. Best is trial 2 with value: 0.2862434898991479.
[I 2025-09-05 21:40:08,953] Trial 4 finished with value: 0.28773467257560525 and parameters: {'n_estimators': 200, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 4}. Best is trial 1 with value: 0.2799209323413995.
[I 2025-09-05 21:40:53,396] Trial 7 finished with value: 0.27757599161064617 and parameters: {'n_estimators': 200, 'max_depth': 15, 'min_samples_split': 5, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.2730393600728001.
[I 2025-09-05 21:40:53,418] Trial 9 finished with value: 0.28853187703149047 and parameters: {'n_estimators': 300, 'max_depth': 20, 'min_samples_split': 5, 'min_samples_leaf': 2}. Best is trial 2 with value: 0.2862434898991479.
[I 2025-09-05 21:41:23,624] Trial 10 finished with value: 0.3359134692845489 and parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 2 with value: 0.2862434898991479.
[I 2025-09-05 21:41:30,759] Trial 5 finished with value: 0.29354471828434964 and parameters: {'n_estimators': 50, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 4}. Best is trial 1 with value: 0.2799209323413995.
[I 2025-09-05 21:42:38,253] Trial 8 finished with value: 0.28726056874302963 and parameters: {'n_estimators': 200, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.2730393600728001.
[I 2025-09-05 21:44:24,238] Trial 6 finished with value: 0.2799209323413995 and parameters: {'n_estimators': 300, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 1 with value: 0.2799209323413995.
[I 2025-09-05 21:44:24,300] Trial 9 finished with value: 0.2767558201591268 and parameters: {'n_estimators': 100, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.2730393600728001.
[I 2025-09-05 21:45:43,798] Trial 11 finished with value: 0.2862380191248139 and parameters: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 11 with value: 0.2862380191248139.
[I 2025-09-05 21:45:50,437] Trial 7 finished with value: 0.28928306653774 and parameters: {'n_estimators': 50, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 1 with value: 0.2799209323413995.
[I 2025-09-05 21:46:00,811] Trial 10 finished with value: 0.3232828898719975 and parameters: {'n_estimators': 300, 'max_depth': 5, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.2730393600728001.
[I 2025-09-05 21:48:19,661] Trial 8 finished with value: 0.3227739449690104 and parameters: {'n_estimators': 300, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 1}. Best is trial 1 with value: 0.2799209323413995.
[I 2025-09-05 21:48:19,679] Trial 11 finished with value: 0.27431587778737715 and parameters: {'n_estimators': 100, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.2730393600728001.
[I 2025-09-05 21:49:01,624] Trial 12 finished with value: 0.2862434898991479 and parameters: {'n_estimators': 300, 'max_depth': 20, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 11 with value: 0.2862380191248139.
[I 2025-09-05 21:49:08,572] Trial 9 finished with value: 0.28928306653774 and parameters: {'n_estimators': 50, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 1 with value: 0.2799209323413995.
[I 2025-09-05 21:49:21,147] Trial 12 finished with value: 0.32184731904998515 and parameters: {'n_estimators': 100, 'max_depth': 5, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.2730393600728001.
[I 2025-09-05 21:52:11,239] Trial 10 finished with value: 0.28681387092769656 and parameters: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 10, 'min_samples_leaf': 2}. Best is trial 1 with value: 0.2799209323413995.
[I 2025-09-05 21:52:22,750] Trial 13 finished with value: 0.27429935525176247 and parameters: {'n_estimators': 100, 'max_depth': 20, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.2730393600728001.
[I 2025-09-05 21:52:22,752] Trial 13 finished with value: 0.2868743937907838 and parameters: {'n_estimators': 200, 'max_depth': 20, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 11 with value: 0.2862380191248139.
[W 2025-09-05 21:53:22,125] Trial 14 failed with parameters: {'n_estimators': 100} because of the following error: StorageInternalError('An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. ').
Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 77, in _create_scoped_session
    yield session
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 586, in set_trial_param
    self._set_trial_param_without_commit(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 598, in _set_trial_param_without_commit
    trial = models.TrialModel.find_or_raise_by_id(trial_id, session)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/models.py", line 270, in find_or_raise_by_id
    trial = query.one_or_none()
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2845, in one_or_none
    return self._iter().one_or_none()
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2903, in _iter
    result = self.session.execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1696, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1631, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context
    self._handle_dbapi_exception(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: SELECT trials.trial_id AS trials_trial_id, trials.number AS trials_number, trials.study_id AS trials_study_id, trials.state AS trials_state, trials.datetime_start AS trials_datetime_start, trials.datetime_complete AS trials_datetime_complete 
FROM trials 
WHERE trials.trial_id = ?]
[parameters: (102,)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/study/_optimize.py", line 201, in _run_trial
    value_or_values = func(trial)
  File "/myriadfs/home/ucnwdma/Scratch/UCL_internship/code/study_manager.py", line 81, in objective
    hyperparams = model_class.get_hyperparameter_space(trial)
  File "/myriadfs/home/ucnwdma/Scratch/UCL_internship/code/models.py", line 272, in get_hyperparameter_space
    'max_depth': trial.suggest_categorical('max_depth', [None, 5, 10, 15, 20]),
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/trial/_trial.py", line 406, in suggest_categorical
    return self._suggest(name, CategoricalDistribution(choices=choices))
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/trial/_trial.py", line 641, in _suggest
    storage.set_trial_param(trial_id, name, param_value_in_internal_repr, distribution)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_cached_storage.py", line 169, in set_trial_param
    self._backend.set_trial_param(trial_id, param_name, param_value_internal, distribution)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 586, in set_trial_param
    self._set_trial_param_without_commit(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 95, in _create_scoped_session
    raise optuna.exceptions.StorageInternalError(message) from e
optuna.exceptions.StorageInternalError: An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. 
[W 2025-09-05 21:53:22,126] Trial 14 failed with value None.
[I 2025-09-05 21:54:44,015] Trial 11 finished with value: 0.28743449710312224 and parameters: {'n_estimators': 300, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 2}. Best is trial 1 with value: 0.2799209323413995.
[I 2025-09-05 21:55:54,112] Trial 14 finished with value: 0.2862380191248139 and parameters: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 11 with value: 0.2862380191248139.
[I 2025-09-05 21:57:47,106] Trial 12 finished with value: 0.2787011564770754 and parameters: {'n_estimators': 300, 'max_depth': 20, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 12 with value: 0.2787011564770754.
[I 2025-09-05 22:00:31,130] Trial 13 finished with value: 0.28686753629134704 and parameters: {'n_estimators': 300, 'max_depth': 20, 'min_samples_split': 10, 'min_samples_leaf': 2}. Best is trial 12 with value: 0.2787011564770754.
[I 2025-09-05 22:02:58,242] Trial 14 finished with value: 0.2787011564770754 and parameters: {'n_estimators': 300, 'max_depth': 20, 'min_samples_split': 2, 'min_samples_leaf': 2}. Best is trial 12 with value: 0.2787011564770754.
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 77, in _create_scoped_session
    yield session
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 625, in set_trial_state_values
    trial = models.TrialModel.find_or_raise_by_id(trial_id, session, for_update=True)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/models.py", line 270, in find_or_raise_by_id
    trial = query.one_or_none()
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2845, in one_or_none
    return self._iter().one_or_none()
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2903, in _iter
    result = self.session.execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1696, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1631, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context
    self._handle_dbapi_exception(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: SELECT trials.trial_id AS trials_trial_id, trials.number AS trials_number, trials.study_id AS trials_study_id, trials.state AS trials_state, trials.datetime_start AS trials_datetime_start, trials.datetime_complete AS trials_datetime_complete 
FROM trials 
WHERE trials.trial_id = ?]
[parameters: (44,)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/study/_optimize.py", line 213, in _run_trial
    updated_state, values, warning_message = _tell_with_warning(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/study/_tell.py", line 175, in _tell_with_warning
    study._storage.set_trial_state_values(frozen_trial._trial_id, state, values)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_cached_storage.py", line 185, in set_trial_state_values
    return self._backend.set_trial_state_values(trial_id, state=state, values=values)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 641, in set_trial_state_values
    trial.datetime_complete = datetime.now()
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 95, in _create_scoped_session
    raise optuna.exceptions.StorageInternalError(message) from e
optuna.exceptions.StorageInternalError: An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/myriadfs/home/ucnwdma/Scratch/UCL_internship/code/study_manager.py", line 97, in run_single_experiment
    best_hyperparams = self.run_hyperparameter_optimization(
  File "/myriadfs/home/ucnwdma/Scratch/UCL_internship/code/study_manager.py", line 85, in run_hyperparameter_optimization
    study.optimize(objective, n_trials=env.N_TRIALS)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/study/study.py", line 490, in optimize
    _optimize(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/study/_optimize.py", line 63, in _optimize
    _optimize_sequential(
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/study/_optimize.py", line 160, in _optimize_sequential
    frozen_trial_id = _run_trial(study, func, catch)
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/site-packages/optuna/study/_optimize.py", line 251, in _run_trial
    assert False, "Should not reach."
AssertionError: Should not reach.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/myriadfs/home/ucnwdma/Scratch/UCL_internship/./code/main.py", line 18, in <module>
    manager.run_nested_cv(fingerprint, model_name, dataset_name)
  File "/myriadfs/home/ucnwdma/Scratch/UCL_internship/code/study_manager.py", line 136, in run_nested_cv
    raise exc
  File "/myriadfs/home/ucnwdma/Scratch/UCL_internship/code/study_manager.py", line 131, in run_nested_cv
    seed_result, test_predictions, test_indices = future.result()
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/home/ucnwdma/miniconda3/envs/internship/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
AssertionError: Should not reach.
